// @ts-check

/**
 * @type {import('cspell').CSpellSettings}
 */
export default {
  useGitignore: true,
  ignorePaths: ['**/pnpm-lock.yaml', 'test/**/*', 'pnpm-workspace.yaml', '**/*.svg', 'patches/**'],
  words: [
    // Names
    'qwik',
    'sonarjs',
    'klona',
    'nuxt',
    'vuejs',
    'unplugin',
    'jsdocs',
    'libxmljs',
    'kramed',
    'signale',
    'opensearchservice',
    'commonmark',
    'shiki',
    'defu',
    'turborepo',
    'marko',
    'intlify',
    'csstree',
    'smarttools',
    'destr',
    'unocss',
    'attw',
    'tsgo',
    'tinyexec',

    // Technical words/terms
    'arraify',
    'renamer',
    'nonconstructor',
    'nonoctal',
    'thenables',
    'callees',
    'pseudorandomness',
    'httponly',
    'lookarounds',
    'chunkname',
    'namepaths',
    'lockfiles',
    'worklet',
    'nums',
    'textnodes',
    'multilines',

    // Misc
    'multicol',
    'bgsound',
    'noembed',
    'scopedslots',
    'setstate',
    'ctsx',
    'cjsx',
    'mtsx',
    'mjsx',
    'rrggbb',
    'ngsrc',
    'ngmodule',
    'andreww',
    'innerhtml',
    'labelledby',
    'activedescendant',
    'proptypes',
    'knipignore',
    'asyncdispose',
    'matchall',

    // Actual-ish English words
    'uncategorized',
    'mischeck',
    'unthrown',
    'promisable',
    'requirable',
    'rethrowing',
    'dedented',
    'curlies',
    'unsanitized',
    'dont',
    'uncapitalize', // TS utility type
  ],
};
