// @ts-check

/**
 * @type {import('cspell').CSpellSettings}
 */
export default {
  useGitignore: true,
  enableGlobDot: true,
  ignorePaths: [
    '.git/**',
    '**/.gitignore',
    '**/pnpm-lock.yaml',
    '.vscode/extensions.json',
    'test/**/*',
    'pnpm-workspace.yaml',
    '**/*.svg',
    'patches/**',
    'scripts/temp/**', // TODO why gitignore doesn't work?
  ],
  words: [
    // Names
    'qwik',
    'sonarjs',
    'klona',
    'nuxt',
    'vuejs',
    'unplugin',
    'jsdocs',
    'libxmljs',
    'kramed',
    'signale',
    'opensearchservice',
    'commonmark',
    'shiki',
    'defu',
    'turborepo',
    'marko',
    'intlify',
    'csstree',
    'smarttools',
    'destr',
    'unocss',
    'attw',
    'tsgo',
    'tinyexec',
    'cleye',
    'neotraverse',
    'knip',
    'tsdown',
    'commitlint',
    'formatjs',
    'messageformat',
    'obug',

    // Technical words/terms
    'arraify',
    'renamer',
    'nonconstructor',
    'nonoctal',
    'thenables',
    'callees',
    'pseudorandomness',
    'httponly',
    'lookarounds',
    'chunkname',
    'namepaths',
    'lockfiles',
    'worklet',
    'nums',
    'textnodes',
    'multilines',
    'greppability',

    // Misc
    'multicol',
    'bgsound',
    'noembed',
    'scopedslots',
    'setstate',
    'ctsx',
    'cjsx',
    'mtsx',
    'mjsx',
    'rrggbb',
    'ngsrc',
    'ngmodule',
    'andreww',
    'innerhtml',
    'labelledby',
    'activedescendant',
    'proptypes',
    'knipignore',
    'asyncdispose',
    'matchall',
    'typegen',

    // Actual-ish English words
    'uncategorized',
    'mischeck',
    'unthrown',
    'promisable',
    'requirable',
    'rethrowing',
    'dedented',
    'curlies',
    'unsanitized',
    'dont',
    'uncapitalize', // TS utility type
    'dups',
    'strikethrough',
  ],
};
