import type {CSpellSettings} from 'cspell';

export default {
  useGitignore: true,
  enableGlobDot: true,
  ignorePaths: [
    '.git/**',
    '**/.gitignore',
    '**/pnpm-lock.yaml',
    '.vscode/extensions.json',
    'test/**/*',
    'pnpm-workspace.yaml',
    '**/*.svg',
    'patches/**',
    '**/temp/**', // Gitignored, but cspell applies `.gitignore` only after walking all (possibly a lot) files in there
    '.claude/worktrees/**', // Ignored via `.git/info/exclude`, which cspell doesn't read
    'data/eslint-plugins-db.json',
    '.all-contributorsrc',
    '.changeset/*.json',
    '.agents/style-guide.md',
  ],
  dictionaries: ['npm', 'node', 'typescript', 'fullstack'],
  words: [
    // Names
    'awscdk',
    'devdeps',
    'qwik',
    'sonarjs',
    'klona',
    'nuxt',
    'vuejs',
    'unplugin',
    'jsdocs',
    'libxmljs',
    'kramed',
    'signale',
    'opensearchservice',
    'commonmark',
    'shiki',
    'defu',
    'turborepo',
    'marko',
    'intlify',
    'csstree',
    'smarttools',
    'destr',
    'unocss',
    'unhead',
    'attw',
    'tsgo',
    'tinyexec',
    'cleye',
    'unutils',
    'verkit',
    'knip',
    'tsdown',
    'commitlint',
    'vitest',
    'formatjs',
    'messageformat',
    'obug',
    'darraghor',
    'oxfmt',
    'splattributes', // Ember
    'tsrx',
    'npmx',
    'gypfile', // package.json field
    'libc', // package.json field
    'oxlint',
    'TSES', // `TSESTree` type from `@typescript-eslint/types`
    'humanwhocodes',
    'scsstree',
    'safeql',
    'solidjs',
    'danielx', // `@danielx/civet`

    // Technical words/terms
    'arrayify',
    'renamer',
    'nonconstructor',
    'nonoctal',
    'thenables',
    'callees',
    'pseudorandomness',
    'httponly',
    'lookarounds',
    'chunkname',
    'namepaths',
    'lockfiles',
    'worklet',
    'nums',
    'textnodes',
    'multilines',
    'greppability',
    'codemod',
    'worktrees',

    // Misc
    'multicol',
    'bgsound',
    'noembed',
    'scopedslots',
    'setstate',
    'ctsx',
    'cjsx',
    'mtsx',
    'mjsx',
    'rrggbb',
    'ngsrc',
    'ngmodule',
    'andreww',
    'innerhtml',
    'labelledby',
    'activedescendant',
    'proptypes',
    'knipignore',
    'asyncdispose',
    'matchall',
    'typegen',
    'viewbox',
    'lychee',
    'smol',

    // Actual-ish English words
    'uncategorized',
    'mischeck',
    'unthrown',
    'promisable',
    'requirable',
    'rethrowing',
    'dedented',
    'curlies',
    'unsanitized',
    'dont',
    'uncapitalize', // TS utility type
    'dups',
    'strikethrough',
    'unexpressible',
    'cooldown',
  ],
} satisfies CSpellSettings;
