nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/css>@eslint/core': 0.17.0
  '@eslint/markdown>@eslint/core': 0.17.0
  '@eslint/plugin-kit@0.3.5>@eslint/core': 0.17.0
  eslint>@eslint/core: 0.17.0

packageImportMethod: clone-or-copy

patchedDependencies:
  eslint-plugin-prettier: patches/eslint-plugin-prettier.patch
  import-meta-resolve: patches/import-meta-resolve.patch
  is-in-editor: patches/is-in-editor.patch

peerDependencyRules:
  allowedVersions:
    '@angular-eslint/eslint-plugin-template>eslint': '*'
    '@angular-eslint/eslint-plugin-template@15>@typescript-eslint/utils': '*'
    '@angular-eslint/eslint-plugin-template@15>eslint': '*'
    '@angular-eslint/utils@15>eslint': '*'
    '@angular-eslint/utils@17>eslint': '*'
    '@typescript-eslint/project-service@8.38>typescript': '*'
    '@typescript-eslint/tsconfig-utils@8.38>typescript': '*'
    '@typescript-eslint/type-utils@7>eslint': '*'
    '@typescript-eslint/typescript-estree@8.38>typescript': '*'
    '@typescript-eslint/utils@5>eslint': '*'
    '@typescript-eslint/utils@7>eslint': '*'
    '@typescript-eslint/utils@8.38>typescript': '*'
    eslint-plugin-no-type-assertion@1.3>eslint: '*'
