import fs from 'node:fs/promises';
import path from 'node:path';
import type {EnabledBy} from '../../../src/config-un/define-config';
import {PLUGIN_PACKAGES_META} from '../../shared/packages-meta';
import {
  CASCADE_LAYOUT,
  CONFIG_PHASES,
  type DiscoveredConfig,
  discoverConfigs,
  isCascadeAnchor,
  readDocumentedMiscGroupConfigs,
} from './configs-reader';

const CONFIGS_DIR = path.join(import.meta.dirname, '../../../src/configs');

const GENERATED_FILE_HEADER = `/* eslint-disable */
// Generated by \`scripts/src/generation/configs.ts\`, do not edit manually\n`;

const CONFIG_KEY_REGEXP = /^[a-z][\dA-Za-z]*$/;

const npmxLink = (packageName: string) => `[\`${packageName}\`](https://npmx.dev/${packageName})`;

const renderPackageCondition = (packageNameAndMaybeRange: string) => {
  const versionDelimiterIndex = packageNameAndMaybeRange.lastIndexOf('@');
  const hasVersionRange = versionDelimiterIndex > 0;
  const packageName = hasVersionRange
    ? packageNameAndMaybeRange.slice(0, versionDelimiterIndex)
    : packageNameAndMaybeRange;
  const versionRange = hasVersionRange
    ? packageNameAndMaybeRange.slice(versionDelimiterIndex + 1)
    : null;
  return `${npmxLink(packageName)}${versionRange ? ` matching \`${versionRange}\`` : ''}`;
};

/**
 * The part of the `@default` line that follows `<=>`. `null` means the Config is unconditionally
 * enabled or disabled
 */
const deriveEnabledByCondition = (enabledBy: EnabledBy): string | null => {
  if (typeof enabledBy === 'boolean' || 'default' in enabledBy) {
    return null;
  }
  if ('package' in enabledBy) {
    return `${renderPackageCondition(enabledBy.package)} package is installed`;
  }
  if ('packages' in enabledBy) {
    const conditions = enabledBy.packages.map(renderPackageCondition);
    return `${[conditions.slice(0, -1).join(', '), conditions.at(-1)].filter(Boolean).join(' or ')} package is installed`;
  }
  if ('packageAbsent' in enabledBy) {
    return `${renderPackageCondition(enabledBy.packageAbsent)} package is NOT installed`;
  }
  if ('pathExists' in enabledBy) {
    return `\`${enabledBy.pathExists}\` directory exists`;
  }
  if ('packageManager' in enabledBy) {
    return `${enabledBy.packageManager} is detected as a used package manager by ${npmxLink('package-manager-detector')}`;
  }
  if ('configDisabled' in enabledBy) {
    return `\`${enabledBy.configDisabled}\` config is **disabled**`;
  }
  return '`defaultConfigsStatus` is set to `misc-enabled`';
};

const renderDefaultTag = (enabledBy: EnabledBy = true) => {
  const isEnabledByDefault =
    typeof enabledBy === 'boolean'
      ? enabledBy
      : 'default' in enabledBy
        ? enabledBy.default
        : /* a conditional Config is enabled when its condition holds */ true;
  const overrides = typeof enabledBy === 'boolean' ? null : enabledBy;
  const condition = [
    overrides?.text || deriveEnabledByCondition(enabledBy),
    overrides?.textAddendum,
  ]
    .filter(Boolean)
    .join(' ');
  return `@default ${isEnabledByDefault}${condition ? ` <=> ${condition}` : ''}`;
};

const PLUGINS_BY_CONFIG_KEY = Map.groupBy(
  Object.entries(PLUGIN_PACKAGES_META).flatMap(([packageName, meta]) =>
    meta.configs.map((configKey) => ({configKey, meta, packageName})),
  ),
  ({configKey}): string => configKey,
);

/**
 * The plugin the `🧩 Main plugin` line of a Config names. A Config served by several plugins says
 * which of them is the main one in `packages-meta.ts`, since a manifest knows nothing about plugins
 */
const resolveMainPlugin = (configKey: string) => {
  const plugins = PLUGINS_BY_CONFIG_KEY.get(configKey) || [];
  const mainPlugins = plugins.filter(({meta}) => meta.isMainPlugin);

  if (plugins.length < 2) {
    return {
      plugin: plugins[0],
      error:
        mainPlugins.length > 0
          ? 'is served by a single plugin, whose `isMainPlugin` marker in `packages-meta.ts` is therefore redundant'
          : null,
    };
  }
  return mainPlugins.length === 1
    ? {plugin: mainPlugins[0], error: null}
    : {
        plugin: undefined,
        error: `is served by ${plugins.length} plugins, exactly one of which must be marked with \`isMainPlugin\` in \`packages-meta.ts\` (${mainPlugins.length} currently marked)`,
      };
};

const renderMainPluginLines = (configKey: string) => {
  const {plugin} = resolveMainPlugin(configKey);
  if (!plugin?.packageName) {
    return [];
  }

  const {pluginDocsUrl} = plugin.meta;
  const docs =
    typeof pluginDocsUrl === 'string' ? {label: 'docs', url: pluginDocsUrl} : pluginDocsUrl;
  return [
    '',
    `🧩 Main plugin: ${npmxLink(plugin.packageName)}`,
    ...(docs ? [`([${docs.label}](${docs.url}))`] : []),
  ];
};

const renderJsDoc = (lines: string[], indent: string) =>
  [
    `${indent}/**`,
    ...lines.map((line) => `${indent} *${line ? ` ${line}` : ''}`),
    `${indent} */`,
  ].join('\n');

const topologicallySort = <T>(
  items: readonly T[],
  getKey: (item: T) => string,
  getDependencies: (item: T) => readonly string[],
) => {
  const itemsByKey = new Map(items.map((item) => [getKey(item), item]));
  const visited = new Set<string>();
  const inProgress = new Set<string>();
  const cycles: string[][] = [];
  const sorted: T[] = [];

  const visit = (key: string, trail: string[]) => {
    if (visited.has(key)) {
      return;
    }
    if (inProgress.has(key)) {
      cycles.push([...trail.slice(trail.indexOf(key)), key]);
      return;
    }
    const item = itemsByKey.get(key);
    if (!item) {
      return;
    }
    inProgress.add(key);
    getDependencies(item).forEach((dependencyKey) => {
      visit(dependencyKey, [...trail, key]);
    });
    inProgress.delete(key);
    visited.add(key);
    sorted.push(item);
  };

  items.forEach((item) => {
    visit(getKey(item), []);
  });

  return {sorted, cycles};
};

const getIsInMiscGroup = ({enabledBy}: DiscoveredConfig['manifest']) =>
  typeof enabledBy === 'object' && 'group' in enabledBy;

const validate = (
  configs: readonly DiscoveredConfig[],
  {documentedMiscGroupConfigs}: {documentedMiscGroupConfigs: readonly string[]},
) => {
  const errors: string[] = [];
  const report = (key: string, message: string) => {
    errors.push(`\`${key}\`: ${message}`);
  };

  const knownKeys = new Set(configs.map(({key}) => key));
  const keysExposingResults = new Set(
    configs.filter(({resultInterfaceName}) => resultInterfaceName).map(({key}) => key),
  );
  const seenKeys = new Set<string>();
  const optionsInterfaceOwners = new Map<string, string>();

  configs.forEach((config) => {
    const {key, manifest, optionsInterfaceName} = config;

    if (!CONFIG_KEY_REGEXP.test(key)) {
      report(key, 'the key must be a non-empty camelCase identifier');
    }
    if (seenKeys.has(key)) {
      report(key, 'duplicate key (also declared in another module)');
    }
    seenKeys.add(key);

    const optionsInterfaceId = `${config.optionsInterfaceFilePath}#${optionsInterfaceName}`;
    const previousOwner = optionsInterfaceOwners.get(optionsInterfaceId);
    if (previousOwner) {
      report(
        key,
        `options interface \`${optionsInterfaceName}\` is already used by the \`${previousOwner}\` Config`,
      );
    }
    optionsInterfaceOwners.set(optionsInterfaceId, key);

    // The generated `UnConfigs` entry references the interface as `import('<module>').<name>`
    if (config.optionsInterfaceFilePath !== config.filePath) {
      report(
        key,
        `options interface \`${optionsInterfaceName}\` must be declared in the Config module itself`,
      );
    }
    if (!config.isOptionsInterfaceExported) {
      report(key, `options interface \`${optionsInterfaceName}\` must be exported`);
    }
    if (config.prose.length === 0) {
      report(
        key,
        `options interface \`${optionsInterfaceName}\` must have a doc comment describing the Config`,
      );
    }
    if (config.prose.some((line) => line.startsWith('@default'))) {
      report(key, 'the `@default` tag is generated, please remove it and use `enabledBy` instead');
    }
    if (config.prose.some((line) => line.startsWith('⚙️ Sub config'))) {
      report(key, 'the `⚙️ Sub config(s)` line is generated, please remove it');
    }
    if (config.prose.some((line) => line.startsWith('🧩 Main plugin'))) {
      report(key, 'the `🧩 Main plugin` line is generated, please remove it');
    }

    const mainPluginError = resolveMainPlugin(key).error;
    if (mainPluginError) {
      report(key, mainPluginError);
    }

    if (manifest.requires && manifest.enabledBy === undefined) {
      report(key, '`requires` is only meaningful together with an explicit `enabledBy`');
    }
    if (
      config.manifestProperties?.length === 1 &&
      config.manifestProperties[0] === 'enabledBy' &&
      typeof manifest.enabledBy === 'boolean'
    ) {
      report(
        key,
        `the manifest only sets \`enabledBy\`, please pass \`${manifest.enabledBy}\` as the second \`defineUnConfig\` argument instead`,
      );
    }
    if (manifest.phase != null && !CONFIG_PHASES.includes(manifest.phase)) {
      report(key, `unknown phase \`${manifest.phase}\``);
    }
    if (typeof manifest.enabledBy === 'object') {
      const {text, textAddendum} = manifest.enabledBy;
      if (text != null && textAddendum != null) {
        report(
          key,
          '`enabledBy.text` replaces the generated text and `enabledBy.textAddendum` appends to it, please keep only one',
        );
      }
      if (text === deriveEnabledByCondition(manifest.enabledBy)) {
        report(key, '`enabledBy.text` repeats the generated text, please remove it');
      }
      if (textAddendum?.trim() === '') {
        report(key, '`enabledBy.textAddendum` adds nothing, please remove it');
      }
    }
    if (
      typeof manifest.enabledBy === 'object' &&
      'configDisabled' in manifest.enabledBy &&
      !knownKeys.has(manifest.enabledBy.configDisabled)
    ) {
      report(
        key,
        `\`enabledBy.configDisabled\` names an unknown Config \`${manifest.enabledBy.configDisabled}\``,
      );
    }
    if (manifest.requires && !config.isRequiredPluginKnown) {
      report(
        key,
        `\`requires.pluginLoadable\` names an unknown plugin \`${manifest.requires.pluginLoadable}\``,
      );
    }

    (['after', 'needs'] as const).forEach((property) => {
      const referencedKeys = manifest[property] || [];
      const seenReferences = new Set<string>();
      referencedKeys.forEach((referencedKey) => {
        if (!knownKeys.has(referencedKey)) {
          report(key, `\`${property}\` names an unknown Config \`${referencedKey}\``);
        }
        if (referencedKey === key) {
          report(key, `\`${property}\` must not name the Config itself`);
        }
        if (seenReferences.has(referencedKey)) {
          report(key, `\`${property}\` lists \`${referencedKey}\` more than once`);
        }
        seenReferences.add(referencedKey);
      });
    });

    (manifest.needs || []).forEach((neededKey) => {
      if (knownKeys.has(neededKey) && !keysExposingResults.has(neededKey)) {
        report(key, `\`needs\` names \`${neededKey}\`, which does not export a result interface`);
      }
    });
  });

  const phaseIndexByKey = new Map(
    configs.map(({key, manifest}) => [key, CONFIG_PHASES.indexOf(manifest.phase || 'default')]),
  );
  configs.forEach(({key, manifest}) => {
    (manifest.after || []).forEach((afterKey) => {
      const ownPhase = phaseIndexByKey.get(key);
      const afterPhase = phaseIndexByKey.get(afterKey);
      if (ownPhase != null && afterPhase != null && ownPhase < afterPhase) {
        report(
          key,
          `\`after\` names \`${afterKey}\`, which belongs to a later phase (\`${manifest.phase || 'default'}\` < \`${configs.find((item) => item.key === afterKey)?.manifest.phase || 'default'}\`)`,
        );
      }
    });
  });

  const documentedMiscGroup = new Set(documentedMiscGroupConfigs);
  const actualMiscGroup = new Set(
    configs.filter(({manifest}) => getIsInMiscGroup(manifest)).map(({key}) => key),
  );
  actualMiscGroup.difference(documentedMiscGroup).forEach((key) => {
    report(key, 'is in the misc group but is not listed in the `defaultConfigsStatus` option docs');
  });
  documentedMiscGroup.difference(actualMiscGroup).forEach((key) => {
    report(key, 'is listed in the `defaultConfigsStatus` option docs but is not in the misc group');
  });

  (['after', 'needs'] as const).forEach((property) => {
    const {cycles} = topologicallySort(
      configs,
      ({key}) => key,
      ({manifest}) => manifest[property] || [],
    );
    cycles.forEach((cycle) => {
      errors.push(`\`${property}\` cycle detected: ${cycle.join(' → ')}`);
    });
  });

  return errors;
};

/**
 * Configs are laid out band by band, in the order the cascade layout lists them: inside a phase,
 * `after` edges decide the order and everything else is sorted by key. The anchors belong to no
 * phase, and so are emitted on the phase boundaries the layout puts them on
 */
const resolveCascadeOrder = (configs: readonly DiscoveredConfig[]) => {
  const byKey = configs.toSorted((a, b) => a.key.localeCompare(b.key));

  return CASCADE_LAYOUT.flatMap((entry) => {
    if (isCascadeAnchor(entry)) {
      return entry;
    }
    const configsInPhase = byKey.filter(({manifest}) => (manifest.phase || 'default') === entry);
    const keysInPhase = new Set(configsInPhase.map(({key}) => key));
    return topologicallySort(
      configsInPhase,
      ({key}) => key,
      ({manifest}) => (manifest.after || []).filter((afterKey) => keysInPhase.has(afterKey)),
    ).sorted.map(({key}) => key);
  });
};

const renderIndexDts = (configs: readonly DiscoveredConfig[], allConfigKeys: readonly string[]) => {
  const properties = configs.map(
    ({key, manifest, optionsInterfaceName, modulePath, prose, subConfigs}) => {
      const subConfigsLine =
        subConfigs.length > 0
          ? [
              '',
              `⚙️ Sub config${subConfigs.length === 1 ? '' : 's'}: ${subConfigs.map((name) => `\`${name}\``).join(', ')}`,
            ]
          : [];
      return `${renderJsDoc([...prose, ...renderMainPluginLines(key), ...subConfigsLine, renderDefaultTag(manifest.enabledBy)], '  ')}
  ${key}: import('${modulePath}').${optionsInterfaceName}<ExtraPlugins>;`;
    },
  );

  const results = configs
    .filter(({resultInterfaceName}) => resultInterfaceName)
    .toSorted((a, b) => a.key.localeCompare(b.key))
    .map(
      ({key, modulePath, resultInterfaceName}) =>
        `  ${key}: import('${modulePath}').${resultInterfaceName} | null;`,
    );

  const configsSupportingArrays = configs
    .filter(({manifest}) => manifest.supportsMultipleConfigs)
    .map(({key}) => `'${key}'`);

  return `${GENERATED_FILE_HEADER}
import type {ExtraPluginsType} from '../config-un/shared';

export type ConfigKey =
${allConfigKeys.map((key) => `  | '${key}'`).join('\n')};

/**
 * Configs already owning a manifest
 */
export type ManifestConfigKey =${configs.length > 0 ? `\n${configs.map(({key}) => `  | '${key}'`).join('\n')}` : ' never'};

/**
 * Configs the user may configure several times by passing an array of options
 */
export type UnConfigsSupportingArraysGenerated =${configsSupportingArrays.length > 0 ? `\n${configsSupportingArrays.map((key) => `  | ${key}`).join('\n')}` : ' never'};

/**
 * What every Config that is read by another Config makes available to it. \`null\` means
 * the Config was disabled
 */
export interface UnConfigResults {
${results.join('\n') || `${' '.repeat(2)}// no Config results yet`}
}

export interface UnConfigsGenerated<ExtraPlugins extends ExtraPluginsType = never> {
${properties.join('\n\n')}
}
`;
};

const renderManifests = (configs: readonly DiscoveredConfig[], cascadeOrder: readonly string[]) => {
  const miscGroupConfigs = configs
    .filter(({manifest}) => getIsInMiscGroup(manifest))
    .map(({key}) => key);

  const serializeStaticFacts = ({manifest}: DiscoveredConfig) =>
    (['enabledBy', 'requires', 'phase', 'after', 'needs', 'supportsMultipleConfigs'] as const)
      .flatMap((property) =>
        manifest[property] === undefined
          ? []
          : [`    ${property}: ${JSON.stringify(manifest[property])},`],
      )
      .join('\n');

  return `${GENERATED_FILE_HEADER}
import type {CascadeAnchor, ConfigModuleLoader} from '../config-un/define-config';
import type {ConfigKey} from './index.gen';

export const CONFIG_MANIFESTS: Partial<Record<ConfigKey, ConfigModuleLoader>> = {
${configs
  .map(
    (config) => `  ${config.key}: {
${serializeStaticFacts(config)}
    load: () => import('${config.modulePath}'),
  },`,
  )
  .join('\n')}
};

/**
 * Configs enabled by \`defaultConfigsStatus: 'misc-enabled'\`
 */
export const MISC_GROUP_CONFIGS = [
${miscGroupConfigs.map((key) => `  '${key}',`).join('\n')}
] as const satisfies readonly ConfigKey[];

/**
 * Resolved cascade order: every Config, plus the anchors marking the places held by the cascade
 * entries that are not Configs
 */
export const CONFIG_ORDER = [
${cascadeOrder.map((entry) => `  '${entry}',`).join('\n')}
] as const satisfies readonly (CascadeAnchor | ConfigKey)[];
`;
};

const generateConfigArtifacts = async () => {
  const [documentedMiscGroupConfigs, {configs, errors: discoveryErrors}] = await Promise.all([
    readDocumentedMiscGroupConfigs(),
    discoverConfigs(),
  ]);

  const errors = [...discoveryErrors, ...validate(configs, {documentedMiscGroupConfigs})];
  if (errors.length > 0) {
    throw new Error(`Invalid Config manifests:\n${errors.map((error) => `- ${error}`).join('\n')}`);
  }

  const cascadeOrder = resolveCascadeOrder(configs);
  const configsByKey = new Map(configs.map((config) => [config.key, config]));
  const orderedConfigs = cascadeOrder.map((key) => configsByKey.get(key)).filter((v) => v != null);

  const allConfigKeys = configs.map(({key}) => key).toSorted();

  return {
    indexDtsCode: renderIndexDts(configs, allConfigKeys),
    manifestsCode: renderManifests(orderedConfigs, cascadeOrder),
    configsCount: orderedConfigs.length,
  };
};

export const writeConfigArtifacts = async (format: (code: string) => Promise<string>) => {
  const {indexDtsCode, manifestsCode, configsCount} = await generateConfigArtifacts();

  await Promise.all([
    format(indexDtsCode).then((code) =>
      fs.writeFile(path.join(CONFIGS_DIR, 'index.gen.d.ts'), code),
    ),
    format(manifestsCode).then((code) =>
      fs.writeFile(path.join(CONFIGS_DIR, 'manifests.gen.ts'), code),
    ),
  ]);

  return {configsCount};
};
