// cspell:ignore heregexes
import {GLOB_CIVET, GLOB_CIVET_COMPILED} from '../constants';
import {
  type ExtraPluginsType,
  type UnAllRuleNames,
  type UnFlatConfigEntryBase,
  assignDefaults,
  defineUnConfig,
} from './index';

/**
 * [Civet](https://civet.dev) support: `.civet` files are compiled to TypeScript (or JavaScript if
 * the `ts` Config is disabled), which the other Configs then lint.
 * Rules that report code generated by the compiler are disabled in the compiled code.
 *
 * 📁 Default `files`: <code>**&#47;*.civet</code>
 */
export interface CivetEslintConfigOptions<
  ExtraPlugins extends ExtraPluginsType = never,
> extends UnFlatConfigEntryBase<ExtraPlugins, 'civet'> {}

const RULES_REPORTING_GENERATED_CODE = [
  // Implicit returns
  'array-callback-return',
  'no-else-return',
  'no-return-assign',
  'sonar/no-redundant-jump',
  'unicorn/no-useless-else',
  'unicorn/prefer-short-arrow-method',
  'unicorn/prefer-ternary',
  // `try` without `catch`
  'consistent-return',
  'no-empty',
  'no-useless-return',
  'unicorn/catch-error-name',
  'unicorn/prefer-optional-catch-binding',
  // `unless` and `when` conditions
  'sonar/no-inverted-boolean-check',
  'unicorn/no-negated-comparison',
  'unicorn/no-negated-condition',
  // Comprehensions with `when`
  'curly',
  // Missing branches, like `if` expressions without `else`
  'no-void',
  // `do` blocks
  'no-lone-blocks',
  // `let x?` declarations and `for first` reductions
  'no-undef-init',
  'unicorn/no-useless-undefined',
  // Declarations merged by the compiler
  'one-var',
  // Injected helpers
  'no-var',
  'prefer-spread',
  'ts/no-explicit-any',
  'unicorn/new-for-builtins',
  'vars-on-top',
  // Pattern matching
  'e18e/prefer-includes-over-regex-test',
  'no-empty-pattern',
  'unicorn/explicit-length-check',
  'unicorn/prefer-simple-condition-first',
  'unicorn/prefer-switch',
  // `case` blocks
  'unicorn/switch-case-braces',
  // Inclusive slices
  'math/no-static-infinity-calculations',
  'no-constant-binary-expression',
  // Negative indexes
  'unicorn/prefer-at',
  // `continue for` and similar
  'no-extra-label',
  // Destructuring in imports and exports
  'no-useless-rename',
  // Optional object properties
  'unicorn/consistent-conditional-object-spread',
  // Interpolated heregexes
  'unicorn/prefer-string-raw',
  // Tee pipes
  'operator-assignment',
  // Parameters renamed by the compiler
  'promise/param-names',
  // TypeScript syntax compiled to JavaScript
  'dot-notation',
  'unicorn/no-empty-file',
  'unicorn/require-module-specifiers',
  // Unquoted strings, like import sources and object keys
  'stylistic/quotes',
  // Layout of the compiled code
  'stylistic/array-bracket-spacing',
  'stylistic/arrow-parens',
  'stylistic/arrow-spacing',
  'stylistic/block-spacing',
  'stylistic/brace-style',
  'stylistic/comma-dangle',
  'stylistic/comma-spacing',
  'stylistic/generator-star-spacing',
  'stylistic/indent',
  'stylistic/indent-binary-ops',
  'stylistic/jsx-closing-bracket-location',
  'stylistic/jsx-closing-tag-location',
  'stylistic/jsx-curly-newline',
  'stylistic/jsx-equals-spacing',
  'stylistic/jsx-one-expression-per-line',
  'stylistic/jsx-wrap-multilines',
  'stylistic/key-spacing',
  'stylistic/keyword-spacing',
  'stylistic/max-statements-per-line',
  'stylistic/member-delimiter-style',
  'stylistic/multiline-ternary',
  'stylistic/no-extra-parens',
  'stylistic/no-multi-spaces',
  'stylistic/no-multiple-empty-lines',
  'stylistic/no-trailing-spaces',
  'stylistic/no-whitespace-before-property',
  'stylistic/object-curly-spacing',
  'stylistic/operator-linebreak',
  'stylistic/padded-blocks',
  'stylistic/semi',
  'stylistic/semi-spacing',
  'stylistic/space-before-blocks',
  'stylistic/space-before-function-paren',
  'stylistic/space-in-parens',
  'stylistic/space-infix-ops',
  'stylistic/type-annotation-spacing',
] satisfies UnAllRuleNames[];

export default defineUnConfig<CivetEslintConfigOptions>('civet', {
  enabledBy: {package: '@danielx/civet'},
  // Rules of the other Configs are disabled
  phase: 'last',
})((context, optionsRaw) => {
  const optionsResolved = assignDefaults(optionsRaw, {});

  const configBuilder = context.createConfigBuilder(optionsResolved, 'civet');

  configBuilder?.addConfig([
    'civet',
    {
      filesDefault: [GLOB_CIVET],
      parseWith: ['civet', context.configsMeta.ts.enabled ? 'ts' : 'js'],
    },
  ]);

  configBuilder
    ?.addConfig([
      'civet/compiled',
      {
        // Compiled code only exists for the files the processor was applied to
        applyUserFilesAndIgnores: false,
        filesDefault: [GLOB_CIVET_COMPILED],
      },
    ])
    .disableBulkRules(RULES_REPORTING_GENERATED_CODE)
    .addOverrides();
});
