import {definePluginMetadata} from './shared';

export default definePluginMetadata('', {
  docsUrl: 'https://eslint.org/docs/latest/rules',
  ruleDocsUrl: (ruleName) => `https://eslint.org/docs/latest/rules/${ruleName}`,
  prettierLanguage: 'js',
  rules: {
    'array-bracket-newline': {prettierIncompatible: true},
    'array-bracket-spacing': {prettierIncompatible: true},
    'array-element-newline': {prettierIncompatible: true},
    'arrow-body-style': {stylistic: true},
    'arrow-parens': {prettierIncompatible: true},
    'arrow-spacing': {prettierIncompatible: true},
    'block-spacing': {prettierIncompatible: true},
    'brace-style': {prettierIncompatible: true},
    camelcase: {stylistic: true},
    'capitalized-comments': {stylistic: true},
    'comma-dangle': {prettierIncompatible: true},
    'comma-spacing': {prettierIncompatible: true},
    'comma-style': {prettierIncompatible: true},
    'computed-property-spacing': {prettierIncompatible: true},
    'consistent-return': {disableInCodeBlocks: 'tooStrict'},
    'consistent-this': {stylistic: true},
    curly: {
      stylistic: true,
      prettierIncompatible: [
        false,
        "`['all']` (our default) is Prettier-safe per `eslint-config-prettier` docs",
      ],
    },
    'dot-location': {prettierIncompatible: true},
    'dot-notation': {stylistic: true},
    'eol-last': {prettierIncompatible: true, disableInCodeBlocks: 'processorDefault'},
    'func-call-spacing': {prettierIncompatible: true},
    'func-name-matching': {stylistic: true},
    'func-names': {stylistic: true},
    'func-style': {stylistic: true},
    'function-call-argument-newline': {prettierIncompatible: true},
    'function-paren-newline': {prettierIncompatible: true},
    'generator-star-spacing': {prettierIncompatible: true},
    'grouped-accessor-pairs': {stylistic: true},
    'implicit-arrow-linebreak': {prettierIncompatible: true},
    indent: {prettierIncompatible: true},
    'indent-legacy': {prettierIncompatible: true},
    'jsx-quotes': {prettierIncompatible: true},
    'key-spacing': {prettierIncompatible: true},
    'keyword-spacing': {prettierIncompatible: true},
    'linebreak-style': {prettierIncompatible: true},
    'lines-around-comment': {prettierIncompatible: true},
    'logical-assignment-operators': {stylistic: true},
    'max-classes-per-file': {stylistic: true, disableInCodeBlocks: 'tooStrict'},
    'max-depth': {stylistic: true},
    'max-len': {prettierIncompatible: true},
    'max-lines': {stylistic: true},
    'max-lines-per-function': {stylistic: true},
    'max-nested-callbacks': {stylistic: true},
    'max-params': {stylistic: true},
    'max-statements': {stylistic: true},
    'max-statements-per-line': {prettierIncompatible: true},
    'multiline-ternary': {prettierIncompatible: true},
    'new-cap': {stylistic: true},
    'new-parens': {prettierIncompatible: true},
    'newline-per-chained-call': {prettierIncompatible: true},
    'no-alert': {disableInCodeBlocks: 'runtimeOnly'},
    'no-await-in-loop': {disableInCodeBlocks: 'runtimeOnly', cliFiles: 'off'},
    'no-confusing-arrow': {prettierIncompatible: true},
    'no-console': {disableInCodeBlocks: 'runtimeOnly', cliFiles: 'off'},
    'no-div-regex': {stylistic: true},
    'no-duplicate-imports': {disableInCodeBlocks: 'imports'},
    'no-else-return': {stylistic: true},
    'no-empty-function': {
      disableInCodeBlocks: 'emptiness',
      disableInTestFiles: [
        true,
        '⚠️ DO NOT FORGET to sync the rules list with the jsdoc description of `tests` config',
      ],
    },
    'no-eval': {disableInCodeBlocks: 'eval'},
    'no-extend-native': {disableInCodeBlocks: 'runtimeOnly'},
    'no-extra-parens': {prettierIncompatible: true},
    'no-extra-semi': {prettierIncompatible: true},
    'no-floating-decimal': {prettierIncompatible: true},
    'no-implicit-coercion': {stylistic: true},
    'no-implied-eval': {disableInCodeBlocks: 'eval'},
    'no-inline-comments': {stylistic: true},
    'no-labels': {disableInCodeBlocks: 'tooStrict'},
    'no-lone-blocks': {disableInCodeBlocks: 'emptiness'},
    'no-lonely-if': {stylistic: true},
    'no-mixed-operators': {prettierIncompatible: true},
    'no-mixed-spaces-and-tabs': {prettierIncompatible: true},
    'no-multi-assign': {stylistic: true},
    'no-multi-spaces': {prettierIncompatible: true},
    'no-multi-str': {stylistic: true},
    'no-multiple-empty-lines': {prettierIncompatible: true},
    'no-negated-condition': {stylistic: true},
    'no-nested-ternary': {stylistic: true},
    'no-new': {disableInCodeBlocks: 'runtimeOnly'},
    'no-new-func': {disableInCodeBlocks: 'eval'},
    'no-plusplus': {stylistic: true},
    'no-promise-executor-return': {disableInCodeBlocks: 'tooStrict'},
    'no-regex-spaces': {stylistic: true},
    'no-restricted-globals': {disableInCodeBlocks: 'tooStrict'},
    'no-return-assign': {stylistic: true},
    'no-script-url': {disableInCodeBlocks: 'tooStrict'},
    'no-sequences': {disableInCodeBlocks: 'tooStrict'},
    'no-shadow': {disableInCodeBlocks: 'tooStrict'},
    'no-spaced-func': {prettierIncompatible: true},
    'no-tabs': {prettierIncompatible: true},
    'no-ternary': {stylistic: true},
    'no-trailing-spaces': {prettierIncompatible: true},
    'no-undef': {disableInCodeBlocks: 'processorDefault'},
    'no-undef-init': {stylistic: true},
    'no-underscore-dangle': {stylistic: true},
    'no-unexpected-multiline': {prettierIncompatible: true},
    'no-unreachable': {disableInCodeBlocks: 'runtimeOnly'},
    'no-unused-expressions': {disableInCodeBlocks: 'processorDefault'},
    'no-unused-labels': {disableInCodeBlocks: 'unused'},
    'no-unused-private-class-members': {disableInCodeBlocks: 'unused'},
    'no-unused-vars': {disableInCodeBlocks: 'processorDefault'},
    'no-useless-assignment': {disableInCodeBlocks: 'unused'},
    'no-useless-concat': {stylistic: true},
    'no-useless-constructor': {disableInCodeBlocks: 'tooStrict'},
    'no-var': {disableInCodeBlocks: 'tooStrict'},
    'no-void': {stylistic: true},
    'no-warning-comments': {stylistic: true},
    'no-whitespace-before-property': {prettierIncompatible: true},
    // cspell:disable-next-line
    'nonblock-statement-body-position': {prettierIncompatible: true},
    'object-curly-newline': {prettierIncompatible: true},
    'object-curly-spacing': {prettierIncompatible: true},
    'object-property-newline': {prettierIncompatible: true},
    'object-shorthand': {stylistic: true},
    'one-var': {stylistic: true},
    'one-var-declaration-per-line': {prettierIncompatible: true},
    'operator-assignment': {stylistic: true},
    'operator-linebreak': {prettierIncompatible: true},
    'padded-blocks': {prettierIncompatible: true, disableInCodeBlocks: 'processorDefault'},
    'prefer-arrow-callback': {stylistic: true},
    'prefer-const': {disableInCodeBlocks: 'tooStrict'},
    'prefer-destructuring': {stylistic: true},
    'prefer-exponentiation-operator': {stylistic: true},
    'prefer-named-capture-group': {stylistic: true},
    'prefer-numeric-literals': {stylistic: true},
    'prefer-object-has-own': {stylistic: true},
    'prefer-object-spread': {stylistic: true},
    'prefer-regex-literals': {stylistic: true},
    'prefer-spread': {stylistic: true},
    'prefer-template': {stylistic: true},
    'quote-props': {prettierIncompatible: true},
    quotes: {prettierIncompatible: true},
    'require-await': {disableInCodeBlocks: 'tooStrict'},
    'rest-spread-spacing': {prettierIncompatible: true},
    semi: {prettierIncompatible: true},
    'semi-spacing': {prettierIncompatible: true},
    'semi-style': {prettierIncompatible: true},
    'sort-imports': {stylistic: true},
    'sort-keys': {stylistic: true},
    'sort-vars': {stylistic: true},
    'space-before-blocks': {prettierIncompatible: true},
    'space-before-function-paren': {prettierIncompatible: true},
    'space-in-parens': {prettierIncompatible: true},
    'space-infix-ops': {prettierIncompatible: true},
    'space-unary-ops': {prettierIncompatible: true},
    strict: {disableInCodeBlocks: 'processorDefault'},
    'switch-colon-spacing': {prettierIncompatible: true},
    'template-curly-spacing': {prettierIncompatible: true},
    'template-tag-spacing': {prettierIncompatible: true},
    'unicode-bom': {disableInCodeBlocks: 'processorDefault'},
    'wrap-iife': {prettierIncompatible: true},
    'wrap-regex': {prettierIncompatible: true},
    'yield-star-spacing': {prettierIncompatible: true},
    yoda: {stylistic: true},
  },
});
