import {definePluginMetadata} from './shared';

export default definePluginMetadata('markdown-preferences', {
  configs: ['markdownPreferences'],
  docsUrl: 'https://ota-meshi.github.io/eslint-plugin-markdown-preferences',
  ruleDocsUrl: (ruleName) =>
    `https://ota-meshi.github.io/eslint-plugin-markdown-preferences/rules/${ruleName}.html`,
  prettierLanguage: 'markdown',
  rules: {
    'atx-heading-closing-sequence': {stylistic: true, prettierIncompatible: true},
    'atx-heading-closing-sequence-length': {stylistic: true, prettierIncompatible: true},
    'blockquote-marker-alignment': {stylistic: true, prettierIncompatible: true},
    'bullet-list-marker-style': {stylistic: true, prettierIncompatible: true},
    'canonical-code-block-language': {stylistic: true},
    'code-fence-length': {stylistic: true, prettierIncompatible: true},
    'code-fence-spacing': {stylistic: true, prettierIncompatible: true},
    'code-fence-style': {stylistic: true, prettierIncompatible: true},
    'custom-container-marker-spacing': {stylistic: true},
    'definitions-last': {stylistic: true},
    'emoji-notation': {stylistic: true},
    'emphasis-delimiters-style': {stylistic: true, prettierIncompatible: true},
    'hard-linebreak-style': {stylistic: true},
    'heading-casing': {autofixDisabled: [true, 'may change the meaning of the text']},
    indent: {stylistic: true, prettierIncompatible: true},
    'level1-heading-style': {stylistic: true},
    'level2-heading-style': {stylistic: true},
    'link-bracket-newline': {stylistic: true, prettierIncompatible: true},
    'link-bracket-spacing': {stylistic: true, prettierIncompatible: true},
    'link-destination-style': {stylistic: true, prettierIncompatible: true},
    'link-paren-newline': {stylistic: true, prettierIncompatible: true},
    'link-paren-spacing': {stylistic: true, prettierIncompatible: true},
    'link-title-style': {stylistic: true, prettierIncompatible: true},
    'list-marker-alignment': {stylistic: true, prettierIncompatible: true},
    'max-len': {prettierIncompatible: true},
    // cspell:disable-next-line
    'no-laziness-blockquotes': {stylistic: true},
    'no-multi-spaces': {stylistic: true, prettierIncompatible: true},
    'no-multiple-empty-lines': {stylistic: true, prettierIncompatible: true},
    'no-tabs': {prettierIncompatible: true},
    'no-text-backslash-linebreak': {stylistic: true},
    'no-trailing-spaces': {stylistic: true, prettierIncompatible: true},
    'ordered-list-marker-sequence': {stylistic: true, prettierIncompatible: true},
    'ordered-list-marker-start': {stylistic: true, prettierIncompatible: true},
    'ordered-list-marker-style': {stylistic: true, prettierIncompatible: true},
    'padded-custom-containers': {stylistic: true},
    'padding-line-between-blocks': {stylistic: true},
    // cspell:disable-next-line
    'prefer-autolinks': {stylistic: true},
    'prefer-fenced-code-blocks': {stylistic: true},
    'prefer-link-reference-definitions': {stylistic: true},
    // cspell:disable-next-line
    'setext-heading-underline-length': {stylistic: true},
    'sort-definitions': {stylistic: true},
    'strikethrough-delimiters-style': {stylistic: true, prettierIncompatible: true},
    'table-header-casing': {autofixDisabled: [true, 'may change the meaning of the text']},
    'table-leading-trailing-pipes': {
      stylistic: true,
      prettierIncompatible: [false, 'agrees with Prettier on alignment'],
    },
    'table-pipe-alignment': {
      stylistic: true,
      prettierIncompatible: [
        false,
        "agrees with Prettier on alignment, except with non-default `proseWrap: 'never'`",
      ],
    },
    'table-pipe-spacing': {
      stylistic: true,
      prettierIncompatible: [false, 'agrees with Prettier on alignment'],
    },
    'thematic-break-character-style': {stylistic: true, prettierIncompatible: true},
    'thematic-break-length': {stylistic: true, prettierIncompatible: true},
    'thematic-break-sequence-pattern': {stylistic: true, prettierIncompatible: true},
  },
});
