import {definePluginMetadata} from './shared';

export default definePluginMetadata('react', {
  configs: ['react'],
  isMainPlugin: true,
  ruleDocsUrl: (ruleName) =>
    `https://github.com/jsx-eslint/eslint-plugin-react/blob/HEAD/docs/rules/${ruleName}.md`,
  prettierLanguage: 'js',
  rules: {
    'boolean-prop-naming': {stylistic: true},
    'destructuring-assignment': {stylistic: true},
    'function-component-definition': {stylistic: true},
    'hook-use-state': {stylistic: true},
    'jsx-boolean-value': {stylistic: true},
    'jsx-child-element-spacing': {stylistic: true, prettierIncompatible: true},
    'jsx-closing-bracket-location': {stylistic: true, prettierIncompatible: true},
    'jsx-closing-tag-location': {stylistic: true, prettierIncompatible: true},
    'jsx-curly-brace-presence': {stylistic: true},
    'jsx-curly-newline': {stylistic: true, prettierIncompatible: true},
    'jsx-curly-spacing': {stylistic: true, prettierIncompatible: true},
    'jsx-equals-spacing': {stylistic: true, prettierIncompatible: true},
    'jsx-first-prop-new-line': {stylistic: true, prettierIncompatible: true},
    'jsx-fragments': {stylistic: true},
    'jsx-handler-names': {stylistic: true},
    'jsx-indent': {stylistic: true, prettierIncompatible: true},
    'jsx-indent-props': {stylistic: true, prettierIncompatible: true},
    'jsx-max-props-per-line': {stylistic: true, prettierIncompatible: true},
    'jsx-newline': {stylistic: true, prettierIncompatible: true},
    'jsx-no-literals': {stylistic: true},
    'jsx-one-expression-per-line': {stylistic: true, prettierIncompatible: true},
    'jsx-pascal-case': {stylistic: true},
    'jsx-props-no-multi-spaces': {stylistic: true, prettierIncompatible: true},
    'jsx-sort-props': {stylistic: true},
    'jsx-space-before-closing': {prettierIncompatible: true},
    'jsx-tag-spacing': {stylistic: true, prettierIncompatible: true},
    'jsx-wrap-multilines': {stylistic: true, prettierIncompatible: true},
    'prefer-es6-class': {stylistic: true},
    'prefer-exact-props': {stylistic: true},
    'prefer-read-only-props': {stylistic: true},
    'self-closing-comp': {stylistic: true},
    'sort-comp': {stylistic: true},
    'sort-default-props': {stylistic: true},
    'sort-prop-types': {stylistic: true},
    'state-in-constructor': {stylistic: true},
    'static-property-placement': {stylistic: true},
    'style-prop-object': {stylistic: true},
  },
});
