import {definePluginMetadata} from './shared';

export default definePluginMetadata('regexp', {
  configs: ['regexp'],
  docsUrl: 'https://ota-meshi.github.io/eslint-plugin-regexp',
  ruleDocsUrl: (ruleName) =>
    `https://ota-meshi.github.io/eslint-plugin-regexp/rules/${ruleName}.html`,
  rules: {
    'grapheme-string-literal': {stylistic: true},
    'hexadecimal-escape': {stylistic: true},
    'letter-case': {stylistic: true},
    'match-any': {stylistic: true},
    negation: {stylistic: true},
    'no-super-linear-backtracking': {disableInCodeBlocks: 'runtimeOnly'},
    'no-unused-capturing-group': {disableInCodeBlocks: 'runtimeOnly'},
    'no-useless-character-class': {stylistic: true},
    'no-useless-flag': {disableInCodeBlocks: 'runtimeOnly'},
    'optimal-quantifier-concatenation': {disableInCodeBlocks: 'runtimeOnly'},
    'prefer-character-class': {stylistic: true},
    'prefer-d': {stylistic: true},
    'prefer-named-backreference': {stylistic: true},
    'prefer-named-capture-group': {stylistic: true},
    'prefer-named-replacement': {stylistic: true},
    'prefer-plus-quantifier': {stylistic: true},
    'prefer-quantifier': {stylistic: true},
    'prefer-question-quantifier': {stylistic: true},
    'prefer-regexp-exec': {stylistic: true},
    'prefer-regexp-test': {stylistic: true},
    'prefer-result-array-groups': {stylistic: true},
    'prefer-star-quantifier': {stylistic: true},
    'prefer-unicode-codepoint-escapes': {stylistic: true},
    'prefer-w': {stylistic: true},
    'sort-alternatives': {stylistic: true},
    'sort-character-class-elements': {stylistic: true},
    'sort-flags': {stylistic: true},
    'unicode-escape': {stylistic: true},
    'use-ignore-case': {stylistic: true},
  },
});
