import {definePluginMetadata} from './shared';

export default definePluginMetadata('sonarjs', {
  configs: ['sonar'],
  docsUrl:
    'https://github.com/SonarSource/SonarJS/blob/HEAD/packages/analysis/src/jsts/rules/README.md',
  gitTag: (version) => ({
    url: `https://github.com/SonarSource/SonarJS/blob/___INSERT-REF-HERE___/packages/analysis/src/jsts/rules/CHANGELOG.md#___INSERT-DATE-HERE___-version-${version.replaceAll(/\D/g, '')}`,
  }),
  rules: {
    'anchor-precedence': {requiresTypeInfo: 'optional'},
    'argument-type': {requiresTypeInfo: 'optional'},
    'arguments-order': {requiresTypeInfo: 'optional'},
    'array-callback-without-return': {requiresTypeInfo: 'optional'},
    'arrow-function-convention': {stylistic: true},
    'assertions-in-tests': {requiresTypeInfo: 'optional'},
    'bitwise-operators': {requiresTypeInfo: 'optional'},
    'call-argument-line': {stylistic: true},
    'class-name': {stylistic: true},
    'class-prototype': {requiresTypeInfo: 'optional'},
    'concise-regex': {requiresTypeInfo: 'optional'},
    'conditional-indentation': {stylistic: true},
    'content-length': {disableInCodeBlocks: 'runtimeOnly'},
    cors: {disableInCodeBlocks: 'runtimeOnly'},
    deprecation: {requiresTypeInfo: 'optional'},
    'destructuring-assignment-syntax': {stylistic: true},
    'different-types-comparison': {requiresTypeInfo: 'optional'},
    'disabled-auto-escaping': {requiresTypeInfo: 'optional'},
    'disabled-resource-integrity': {requiresTypeInfo: 'optional'},
    'duplicates-in-character-class': {requiresTypeInfo: 'optional'},
    'empty-string-repetition': {requiresTypeInfo: 'optional'},
    'existing-groups': {requiresTypeInfo: 'optional'},
    'file-uploads': {disableInCodeBlocks: 'runtimeOnly'},
    'function-name': {stylistic: true},
    'function-return-type': {requiresTypeInfo: 'optional'},
    'in-operator-type-error': {requiresTypeInfo: 'optional'},
    'index-of-compare-to-positive-number': {requiresTypeInfo: 'optional'},
    'jsx-no-leaked-render': {requiresTypeInfo: 'optional'},
    'max-lines': {stylistic: true},
    'max-lines-per-function': {stylistic: true},
    'max-switch-cases': {stylistic: true},
    'max-union-size': {stylistic: true},
    'new-operator-misuse': {requiresTypeInfo: 'optional'},
    'no-alphabetical-sort': {requiresTypeInfo: 'optional'},
    'no-array-delete': {requiresTypeInfo: 'optional'},
    'no-associative-arrays': {requiresTypeInfo: 'optional'},
    'no-async-constructor': {requiresTypeInfo: 'optional'},
    'no-clear-text-protocols': {disableInCodeBlocks: 'tooStrict', disableInTestFiles: true},
    'no-collection-size-mischeck': {requiresTypeInfo: 'optional'},
    'no-control-regex': {requiresTypeInfo: 'optional'},
    'no-empty-after-reluctant': {requiresTypeInfo: 'optional'},
    'no-empty-alternatives': {requiresTypeInfo: 'optional'},
    'no-empty-character-class': {requiresTypeInfo: 'optional'},
    'no-empty-collection': {disableInCodeBlocks: 'runtimeOnly'},
    'no-empty-group': {requiresTypeInfo: 'optional'},
    'no-for-in-iterable': {requiresTypeInfo: 'optional'},
    'no-global-this': {disableInCodeBlocks: 'tooStrict'},
    'no-globals-shadowing': {disableInCodeBlocks: 'runtimeOnly'},
    'no-hardcoded-ip': {disableInTestFiles: true},
    'no-hardcoded-passwords': {disableInTestFiles: true},
    'no-hardcoded-secrets': {disableInTestFiles: true},
    'no-identical-functions': {disableInCodeBlocks: [false, 'TODO: reason was not recorded']},
    'no-ignored-exceptions': {disableInCodeBlocks: 'tooStrict'},
    'no-ignored-return': {requiresTypeInfo: 'optional'},
    'no-in-misuse': {requiresTypeInfo: 'optional'},
    'no-incompatible-assertion-types': {requiresTypeInfo: 'optional'},
    'no-inconsistent-returns': {requiresTypeInfo: 'optional'},
    'no-incorrect-string-concat': {requiresTypeInfo: 'optional'},
    'no-invalid-regexp': {requiresTypeInfo: 'optional'},
    'no-inverted-boolean-check': {stylistic: true},
    'no-misleading-array-reverse': {requiresTypeInfo: 'optional'},
    'no-misleading-character-class': {requiresTypeInfo: 'optional'},
    'no-redundant-optional': {requiresTypeInfo: 'optional', stylistic: true},
    'no-regex-spaces': {requiresTypeInfo: 'optional'},
    'no-require-or-define': {requiresTypeInfo: 'optional'},
    'no-return-type-any': {requiresTypeInfo: 'optional'},
    'no-same-line-conditional': {stylistic: true},
    'no-selector-parameter': {requiresTypeInfo: 'optional'},
    'no-session-cookies-on-static-assets': {disableInCodeBlocks: 'runtimeOnly'},
    'no-small-switch': {stylistic: true},
    'no-tab': {stylistic: true},
    'no-try-promise': {requiresTypeInfo: 'optional'},
    'no-undefined-argument': {requiresTypeInfo: 'optional', stylistic: true},
    'no-undefined-assignment': {stylistic: true},
    'no-useless-intersection': {requiresTypeInfo: 'optional'},
    'non-number-in-arithmetic-expression': {requiresTypeInfo: 'optional'},
    'null-dereference': {requiresTypeInfo: 'optional'},
    'operation-returning-nan': {requiresTypeInfo: 'optional'},
    'post-message': {requiresTypeInfo: 'optional'},
    'prefer-immediate-return': {requiresTypeInfo: 'optional'},
    'prefer-read-only-props': {requiresTypeInfo: 'optional', stylistic: true},
    'prefer-regexp-exec': {requiresTypeInfo: 'optional', stylistic: true},
    'prefer-single-boolean-return': {stylistic: true},
    'production-debug': {disableInCodeBlocks: 'runtimeOnly'},
    'public-static-readonly': {stylistic: true},
    'reduce-initial-value': {requiresTypeInfo: 'optional'},
    'regex-complexity': {requiresTypeInfo: 'optional'},
    'session-regeneration': {disableInCodeBlocks: 'runtimeOnly'},
    'shorthand-property-grouping': {stylistic: true},
    'single-char-in-character-classes': {requiresTypeInfo: 'optional'},
    'single-character-alternation': {requiresTypeInfo: 'optional', stylistic: true},
    'slow-regex': {requiresTypeInfo: 'optional'},
    'sql-queries': {requiresTypeInfo: 'optional'},
    'strings-comparison': {requiresTypeInfo: 'optional'},
    'super-linear-regex': {disableInCodeBlocks: 'runtimeOnly'},
    'unicode-aware-regex': {requiresTypeInfo: 'optional'},
    'unused-import': {requiresTypeInfo: 'optional'},
    'unused-named-groups': {requiresTypeInfo: 'optional'},
    'use-type-alias': {stylistic: true},
    'values-not-convertible-to-numbers': {requiresTypeInfo: 'optional'},
    'variable-name': {stylistic: true},
    'void-use': {requiresTypeInfo: 'optional'},
    'x-powered-by': {disableInCodeBlocks: 'runtimeOnly'},
  },
});
