import {definePluginMetadata} from './shared';

export default definePluginMetadata('stylistic', {
  configs: ['stylistic'],
  docsUrl: 'https://eslint.style',
  ruleDocsUrl: (ruleName) => `https://eslint.style/rules/${ruleName}`,
  suggestedPrefix: ['@stylistic', 'more concise and convenient to use; `@` feels redundant'],
  prettierLanguage: 'js',
  allRulesStylistic: true,
  rules: {
    'array-bracket-newline': {prettierIncompatible: true},
    'array-bracket-spacing': {prettierIncompatible: true},
    'array-element-newline': {prettierIncompatible: true},
    'arrow-parens': {prettierIncompatible: true},
    'arrow-spacing': {prettierIncompatible: true},
    'block-spacing': {prettierIncompatible: true},
    'brace-style': {prettierIncompatible: true},
    'comma-dangle': {prettierIncompatible: true},
    'comma-spacing': {prettierIncompatible: true},
    'comma-style': {prettierIncompatible: true},
    'computed-property-spacing': {prettierIncompatible: true},
    'curly-newline': {prettierIncompatible: true},
    'dot-location': {prettierIncompatible: true},
    'eol-last': {prettierIncompatible: true},
    'exp-jsx-props-style': {prettierIncompatible: true},
    'exp-list-style': {prettierIncompatible: true},
    'function-call-argument-newline': {prettierIncompatible: true},
    'function-call-spacing': {prettierIncompatible: true},
    'function-paren-newline': {prettierIncompatible: true},
    'generator-star-spacing': {prettierIncompatible: true},
    'implicit-arrow-linebreak': {prettierIncompatible: true},
    indent: {prettierIncompatible: true},
    'indent-binary-ops': {prettierIncompatible: true},
    'jsx-child-element-spacing': {prettierIncompatible: true},
    'jsx-closing-bracket-location': {prettierIncompatible: true},
    'jsx-closing-tag-location': {prettierIncompatible: true},
    'jsx-curly-newline': {prettierIncompatible: true},
    'jsx-curly-spacing': {prettierIncompatible: true},
    'jsx-equals-spacing': {prettierIncompatible: true},
    'jsx-first-prop-new-line': {prettierIncompatible: true},
    'jsx-function-call-newline': {prettierIncompatible: true},
    'jsx-indent': {prettierIncompatible: true},
    'jsx-indent-props': {prettierIncompatible: true},
    'jsx-max-props-per-line': {prettierIncompatible: true},
    'jsx-newline': {prettierIncompatible: true},
    'jsx-one-expression-per-line': {prettierIncompatible: true},
    'jsx-props-no-multi-spaces': {prettierIncompatible: true},
    'jsx-quotes': {prettierIncompatible: true},
    'jsx-tag-spacing': {prettierIncompatible: true},
    'jsx-wrap-multilines': {prettierIncompatible: true},
    'key-spacing': {prettierIncompatible: true},
    'keyword-spacing': {prettierIncompatible: true},
    'linebreak-style': {prettierIncompatible: true},
    'lines-around-comment': {prettierIncompatible: true},
    'max-len': {prettierIncompatible: true},
    'max-statements-per-line': {prettierIncompatible: true},
    'member-delimiter-style': {prettierIncompatible: true},
    'multiline-ternary': {prettierIncompatible: true},
    'new-parens': {prettierIncompatible: true},
    'newline-per-chained-call': {prettierIncompatible: true},
    'no-confusing-arrow': {prettierIncompatible: true},
    'no-extra-parens': {prettierIncompatible: true},
    'no-extra-semi': {prettierIncompatible: true},
    'no-floating-decimal': {prettierIncompatible: true},
    'no-mixed-operators': {prettierIncompatible: true},
    'no-mixed-spaces-and-tabs': {prettierIncompatible: true},
    'no-multi-spaces': {prettierIncompatible: true},
    'no-multiple-empty-lines': {prettierIncompatible: true},
    'no-tabs': {prettierIncompatible: true},
    'no-trailing-spaces': {prettierIncompatible: true},
    'no-whitespace-before-property': {prettierIncompatible: true},
    // cspell:disable-next-line
    'nonblock-statement-body-position': {prettierIncompatible: true},
    'object-curly-newline': {prettierIncompatible: true},
    'object-curly-spacing': {prettierIncompatible: true},
    'object-property-newline': {prettierIncompatible: true},
    'one-var-declaration-per-line': {prettierIncompatible: true},
    'operator-linebreak': {prettierIncompatible: true},
    'padded-blocks': {prettierIncompatible: true},
    'quote-props': {prettierIncompatible: true},
    quotes: {
      prettierIncompatible: [
        false,
        'by default this rule is configured in a Prettier-compatible way by us',
      ],
    },
    'rest-spread-spacing': {prettierIncompatible: true},
    semi: {prettierIncompatible: true},
    'semi-spacing': {prettierIncompatible: true},
    'semi-style': {prettierIncompatible: true},
    'space-before-blocks': {prettierIncompatible: true},
    'space-before-function-paren': {prettierIncompatible: true},
    'space-in-parens': {prettierIncompatible: true},
    'space-infix-ops': {prettierIncompatible: true},
    'space-unary-ops': {prettierIncompatible: true},
    'switch-colon-spacing': {prettierIncompatible: true},
    'template-curly-spacing': {prettierIncompatible: true},
    'template-tag-spacing': {prettierIncompatible: true},
    'type-annotation-spacing': {prettierIncompatible: true},
    'type-generic-spacing': {prettierIncompatible: true},
    'type-named-tuple-spacing': {prettierIncompatible: true},
    'wrap-iife': {prettierIncompatible: true},
    'wrap-regex': {prettierIncompatible: true},
    'yield-star-spacing': {prettierIncompatible: true},
  },
});
