import {definePluginMetadata} from './shared';

export default definePluginMetadata('ts', {
  configs: ['ts'],
  isMainPlugin: true,
  docsUrl: 'https://typescript-eslint.io',
  ruleDocsUrl: (ruleName) => `https://typescript-eslint.io/rules/${ruleName}`,
  suggestedPrefix: [
    '@typescript-eslint',
    'more concise and convenient to use; `@` feels redundant',
  ],
  rules: {
    'adjacent-overload-signatures': {stylistic: true},
    'array-type': {stylistic: true},
    'ban-ts-comment': {stylistic: true, disableInCodeBlocks: 'runtimeOnly'},
    'class-literal-property-style': {stylistic: true},
    'class-methods-use-this': {disableInCodeBlocks: 'runtimeOnly'},
    'consistent-generic-constructors': {stylistic: true},
    'consistent-indexed-object-style': {stylistic: true},
    'consistent-type-assertions': {stylistic: true},
    'consistent-type-definitions': {stylistic: true},
    'consistent-type-exports': {stylistic: true},
    'consistent-type-imports': {
      stylistic: true,
      disableInCodeBlocks: [false, 'only reads how the snippet itself uses each import'],
    },
    'dot-notation': {stylistic: true},
    'explicit-function-return-type': {disableInCodeBlocks: 'tooStrict'},
    'max-params': {stylistic: true},
    'member-ordering': {stylistic: true},
    'method-signature-style': {
      autofixDisabled: [
        true,
        'a property signature checks its parameters more strictly than a method one, so the fix can break existing assignments',
      ],
      disableInCodeBlocks: 'tooStrict',
    },
    'naming-convention': {
      requiresTypeInfo: [
        'optional',
        'the plugin reports it as type-aware, but the rule asks for the services leniently and only loses the checks that need a type',
      ],
      stylistic: true,
    },
    'no-confusing-non-null-assertion': {stylistic: true},
    'no-empty-function': {disableInCodeBlocks: 'emptiness', disableInTestFiles: true},
    'no-explicit-any': {disableInCodeBlocks: 'tooStrict'},
    'no-extraneous-class': {disableInCodeBlocks: 'tooStrict', disableInTestFiles: true},
    'no-import-type-side-effects': {disableInCodeBlocks: 'runtimeOnly'},
    'no-inferrable-types': {stylistic: true},
    'no-namespace': {disableInCodeBlocks: 'tooStrict'},
    'no-non-null-assertion': {disableInCodeBlocks: 'tooStrict'},
    'no-redeclare': {disableInCodeBlocks: 'runtimeOnly'},
    'no-require-imports': {disableInCodeBlocks: 'runtimeOnly'},
    'no-unnecessary-boolean-literal-compare': {stylistic: true},
    'no-unnecessary-template-expression': {stylistic: true},
    'no-unnecessary-type-arguments': {
      stylistic: true,
      autofixDisabled: [true, 'could remove type aliases'],
    },
    'no-unnecessary-type-assertion': {
      stylistic: [
        false,
        'removing an assertion it reports can still break type checking, for example when a variable in a loop ends up inferring its type from itself',
      ],
    },
    'no-unsafe-function-type': {disableInCodeBlocks: 'tooStrict'},
    'no-unused-expressions': {disableInCodeBlocks: 'unused'},
    'no-unused-vars': {disableInCodeBlocks: 'unused'},
    'no-use-before-define': {disableInCodeBlocks: 'runtimeOnly'},
    'no-useless-empty-export': {disableInCodeBlocks: 'tooStrict'},
    'non-nullable-type-assertion-style': {stylistic: true},
    'prefer-as-const': {stylistic: true},
    'prefer-destructuring': {stylistic: true},
    'prefer-find': {
      stylistic: [
        false,
        'the dedicated method stops calling the predicate at the first match, which a predicate with side effects observes',
      ],
    },
    'prefer-for-of': {stylistic: true},
    'prefer-function-type': {stylistic: true},
    'prefer-includes': {stylistic: true},
    'prefer-nullish-coalescing': {stylistic: true},
    'prefer-optional-chain': {stylistic: true},
    'prefer-readonly': {stylistic: true},
    'prefer-regexp-exec': {stylistic: true},
    'prefer-string-starts-ends-with': {stylistic: true},
    'return-await': {stylistic: true},
    'triple-slash-reference': {stylistic: true},
    'unified-signatures': {stylistic: true},
    'use-unknown-in-catch-callback-variable': {stylistic: true},
  },
});
