import {definePluginMetadata} from './shared';

export default definePluginMetadata('unicorn', {
  configs: ['unicorn'],
  docsUrl: 'https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/readme.md',
  ruleDocsUrl: (ruleName) =>
    `https://github.com/sindresorhus/eslint-plugin-unicorn/blob/HEAD/docs/rules/${ruleName}.md`,
  prettierLanguage: 'js',
  rules: {
    'better-dom-traversing': {stylistic: true},
    'better-regex': {stylistic: true},
    'catch-error-name': {stylistic: true, autofixDisabled: true},
    'consistent-arrow-return-style': {stylistic: true},
    'consistent-assert': {stylistic: true},
    'consistent-boolean-name': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'consistent-class-member-order': {stylistic: true},
    'consistent-conditional-object-spread': {stylistic: true},
    'consistent-date-clone': {stylistic: true},
    'consistent-destructuring': {stylistic: true},
    'consistent-existence-index-check': {stylistic: true, autofixDisabled: true},
    'consistent-export-decorator-position': {stylistic: true},
    'consistent-function-scoping': {disableInCodeBlocks: 'performance'},
    'consistent-template-literal-escape': {stylistic: true},
    'consistent-tuple-labels': {stylistic: true},
    'default-export-style': {stylistic: true},
    'dom-node-dataset': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'empty-brace-spaces': {stylistic: true, prettierIncompatible: true},
    'escape-case': {stylistic: true},
    'explicit-length-check': {
      stylistic: true,
      autofixDisabled: [true, 'wrong auto-fixes'],
    },
    'filename-case': {stylistic: true},
    'import-style': {stylistic: true},
    'iteration-fallback-style': {stylistic: true},
    'no-abusive-eslint-disable': {disableInCodeBlocks: [false, 'TODO: reason was not recorded']},
    'no-array-callback-reference': {requiresTypeInfo: 'optional'},
    'no-array-fill-with-reference-type': {requiresTypeInfo: ['optional', 'indirect']},
    'no-array-front-mutation': {requiresTypeInfo: ['optional', 'indirect']},
    'no-array-method-this-argument': {requiresTypeInfo: ['optional', 'indirect']},
    'no-array-reduce': {requiresTypeInfo: ['optional', 'indirect']},
    'no-array-reverse': {requiresTypeInfo: ['optional', 'indirect']},
    'no-array-sort': {requiresTypeInfo: ['optional', 'indirect']},
    'no-array-sort-for-min-max': {requiresTypeInfo: ['optional', 'indirect']},
    'no-array-splice': {requiresTypeInfo: 'optional'},
    'no-asterisk-prefix-in-documentation-comments': {stylistic: true},
    'no-async-promise-finally': {requiresTypeInfo: 'optional'},
    'no-await-expression-member': {stylistic: true},
    'no-boolean-sort-comparator': {requiresTypeInfo: ['optional', 'indirect']},
    'no-chained-comparison': {requiresTypeInfo: ['optional', 'indirect']},
    'no-collection-bracket-access': {requiresTypeInfo: ['optional', 'indirect']},
    'no-computed-property-existence-check': {requiresTypeInfo: ['optional', 'indirect']},
    'no-confusing-array-splice': {requiresTypeInfo: ['optional', 'indirect']},
    'no-confusing-array-with': {requiresTypeInfo: ['optional', 'indirect']},
    'no-console-spaces': {stylistic: [false, 'TODO: reason was not recorded']},
    'no-duplicate-loops': {requiresTypeInfo: ['optional', 'indirect']},
    'no-for-each': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'no-for-loop': {requiresTypeInfo: 'optional', stylistic: true},
    'no-hex-escape': {stylistic: true},
    'no-immediate-mutation': {stylistic: true},
    'no-invalid-character-comparison': {requiresTypeInfo: ['optional', 'indirect']},
    'no-invalid-well-known-symbol-methods': {requiresTypeInfo: 'optional'},
    'no-keyword-prefix': {stylistic: true},
    'no-late-event-control': {requiresTypeInfo: ['optional', 'indirect']},
    'no-lonely-if': {stylistic: true},
    'no-loop-iterable-mutation': {requiresTypeInfo: ['optional', 'indirect']},
    'no-magic-array-flat-depth': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'no-mismatched-map-key': {requiresTypeInfo: ['optional', 'indirect']},
    'no-named-default': {stylistic: true},
    'no-negated-array-predicate': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'no-negated-comparison': {stylistic: true},
    'no-negated-condition': {stylistic: true},
    'no-negation-in-equality-check': {stylistic: true},
    'no-nested-ternary': {stylistic: true, prettierIncompatible: true},
    'no-new-array': {requiresTypeInfo: ['optional', 'indirect']},
    'no-new-buffer': {
      requiresTypeInfo: [
        false,
        'the imported number check is AST-only; its checker-backed sibling is a different export',
      ],
    },
    'no-non-function-verb-prefix': {requiresTypeInfo: 'optional'},
    'no-null': {stylistic: true},
    'no-object-methods-with-collections': {requiresTypeInfo: 'optional'},
    'no-optional-chaining-on-undeclared-variable': {disableInCodeBlocks: 'runtimeOnly'},
    'no-process-exit': {disableInCodeBlocks: 'runtimeOnly', cliFiles: 'off'},
    'no-redundant-comparison': {stylistic: true},
    'no-return-array-push': {requiresTypeInfo: ['optional', 'indirect']},
    'no-static-only-class': {disableInCodeBlocks: 'tooStrict'},
    'no-subtraction-comparison': {
      requiresTypeInfo: [
        false,
        'the imported number check is AST-only; its checker-backed sibling is a different export',
      ],
      stylistic: true,
    },
    'no-this-assignment': {stylistic: true},
    'no-top-level-side-effects': {disableInCodeBlocks: 'runtimeOnly'},
    'no-transition-all': {requiresTypeInfo: 'optional'},
    'no-typeof-undefined': {stylistic: true},
    'no-uncalled-method': {requiresTypeInfo: ['optional', 'indirect']},
    'no-unnecessary-array-flat-depth': {requiresTypeInfo: ['optional', 'indirect']},
    'no-unnecessary-array-flat-map': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'no-unnecessary-array-splice-count': {
      requiresTypeInfo: ['optional', 'indirect'],
      stylistic: true,
    },
    'no-unnecessary-boolean-comparison': {
      requiresTypeInfo: ['optional', 'indirect'],
      stylistic: true,
    },
    'no-unnecessary-fetch-options': {requiresTypeInfo: 'optional', stylistic: true},
    'no-unnecessary-global-this': {stylistic: true},
    'no-unnecessary-nested-ternary': {stylistic: true},
    'no-unnecessary-slice-end': {requiresTypeInfo: ['optional', 'indirect']},
    'no-unnecessary-splice': {
      requiresTypeInfo: ['optional', 'indirect'],
      stylistic: [
        false,
        'since it also reports no-op `splice()` calls, i.e. potentially broken code',
      ],
    },
    'no-unnecessary-string-trim': {requiresTypeInfo: ['optional', 'indirect']},
    'no-unreadable-array-destructuring': {stylistic: true},
    'no-unreadable-for-of-expression': {requiresTypeInfo: ['optional', 'indirect']},
    'no-unreadable-iife': {stylistic: true},
    'no-unsafe-buffer-conversion': {requiresTypeInfo: 'optional'},
    'no-unsafe-promise-all-settled-values': {requiresTypeInfo: 'optional'},
    'no-unsafe-property-key': {requiresTypeInfo: 'optional'},
    'no-unsafe-string-replacement': {
      requiresTypeInfo: ['optional', 'indirect'],
      disableInCodeBlocks: 'tooStrict',
    },
    'no-unused-array-method-return': {
      requiresTypeInfo: ['optional', 'indirect'],
      disableInCodeBlocks: 'runtimeOnly',
    },
    'no-useless-boolean-cast': {requiresTypeInfo: 'optional', stylistic: true},
    'no-useless-coercion': {requiresTypeInfo: 'optional', stylistic: true},
    'no-useless-collection-argument': {stylistic: true},
    'no-useless-concat': {stylistic: true},
    'no-useless-continue': {stylistic: true},
    'no-useless-else': {stylistic: true},
    'no-useless-fallback-in-spread': {stylistic: true},
    'no-useless-iterator-to-array': {
      requiresTypeInfo: [
        false,
        'the imported unwrap helper is AST-only, it just lives in a checker-backed module',
      ],
    },
    'no-useless-length-check': {requiresTypeInfo: ['optional', 'indirect']},
    'no-useless-logical-operand': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'no-useless-override': {requiresTypeInfo: 'optional'},
    'no-useless-spread': {requiresTypeInfo: ['optional', 'indirect']},
    'no-useless-template-literals': {requiresTypeInfo: 'optional', stylistic: true},
    'no-useless-undefined': {autofixDisabled: true},
    'no-zero-fractions': {stylistic: true},
    'number-literal-case': {stylistic: true, prettierIncompatible: true},
    'numeric-separators-style': {stylistic: true},
    'prefer-abort-signal-any': {requiresTypeInfo: 'optional'},
    'prefer-add-event-listener': {stylistic: true},
    'prefer-add-event-listener-options': {stylistic: true},
    'prefer-aggregate-error': {requiresTypeInfo: 'optional'},
    'prefer-array-find': {
      requiresTypeInfo: ['optional', 'indirect'],
      stylistic: [false, 'TODO: reason was not recorded'],
    },
    'prefer-array-flat': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-array-flat-map': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-array-from-async': {stylistic: true},
    'prefer-array-from-map': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-array-from-range': {stylistic: true},
    'prefer-array-index-of': {
      requiresTypeInfo: [
        false,
        'the shared array search rule only asks about types when told to check a boolean predicate, which this rule does not',
      ],
      stylistic: true,
    },
    'prefer-array-iterable-methods': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-array-slice': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-array-some': {
      requiresTypeInfo: ['optional', 'indirect'],
      stylistic: [
        false,
        'a falsy found element flips the check, and the filtered length form calls the predicate for every element',
      ],
    },
    'prefer-at': {stylistic: true},
    'prefer-await': {requiresTypeInfo: 'optional'},
    'prefer-bigint-literals': {stylistic: true},
    'prefer-block-statement-over-iife': {stylistic: true},
    'prefer-boolean-return': {stylistic: true},
    'prefer-class-fields': {stylistic: true},
    'prefer-classlist-toggle': {stylistic: true},
    'prefer-code-point': {
      stylistic: true,
      disableInCodeBlocks: [false, 'TODO: reason was not recorded'],
    },
    'prefer-continue': {stylistic: true},
    'prefer-date-now': {stylistic: true},
    'prefer-default-parameters': {
      stylistic: [
        false,
        'a default parameter only applies to undefined, while the reassignment it replaces also catches other falsy values, and the arity changes',
      ],
    },
    'prefer-direct-iteration': {requiresTypeInfo: 'optional', stylistic: true},
    'prefer-dispose': {requiresTypeInfo: 'optional'},
    'prefer-dom-node-append': {stylistic: true},
    'prefer-dom-node-dataset': {stylistic: true},
    'prefer-dom-node-remove': {stylistic: true},
    'prefer-dom-node-replace-children': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-dom-node-text-content': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-early-return': {stylistic: true},
    'prefer-else-if': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-export-from': {stylistic: true},
    'prefer-flat-math-min-max': {stylistic: true},
    'prefer-global-number-constants': {stylistic: true},
    'prefer-global-this': {stylistic: true},
    'prefer-group-by': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-has-check': {requiresTypeInfo: 'optional'},
    'prefer-identifier-import-export-specifiers': {stylistic: true},
    'prefer-import-meta-properties': {stylistic: true},
    'prefer-includes': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-includes-over-repeated-comparisons': {stylistic: true},
    'prefer-iterable-in-constructor': {stylistic: true},
    'prefer-iterator-concat': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-iterator-helpers': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-iterator-to-array': {stylistic: true},
    'prefer-keyboard-event-key': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-location-assign': {stylistic: true},
    'prefer-logical-operator-over-ternary': {stylistic: true},
    'prefer-math-min-max': {stylistic: true},
    'prefer-math-trunc': {stylistic: [false, 'the bitwise forms it reports wrap above 2**31']},
    'prefer-minimal-ternary': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-modern-dom-apis': {requiresTypeInfo: 'optional', stylistic: true},
    'prefer-modern-math-apis': {
      stylistic: [
        false,
        'the dedicated methods disagree with the arithmetic they replace in the last digit, and at the extremes',
      ],
    },
    'prefer-native-coercion-functions': {stylistic: true},
    'prefer-negative-index': {stylistic: true},
    'prefer-node-protocol': {stylistic: true},
    'prefer-number-properties': {
      requiresTypeInfo: [
        false,
        'the imported number check is AST-only; its checker-backed sibling is a different export',
      ],
      stylistic: true,
    },
    'prefer-object-define-properties': {stylistic: true},
    'prefer-object-from-entries': {stylistic: true},
    'prefer-object-iterable-methods': {stylistic: true},
    'prefer-observer-apis': {requiresTypeInfo: 'optional'},
    'prefer-optional-catch-binding': {disableInCodeBlocks: 'tooStrict'},
    'prefer-path2d': {requiresTypeInfo: 'optional'},
    'prefer-private-class-fields': {
      autofixDisabled: [
        true,
        'as per the rule description itself, it skips some patterns that could be used to access autofixed non-private fields',
      ],
    },
    'prefer-promise-with-resolvers': {stylistic: true},
    'prefer-prototype-methods': {stylistic: true},
    'prefer-query-selector': {stylistic: true},
    'prefer-reflect-apply': {stylistic: true},
    'prefer-regexp-escape': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-regexp-test': {requiresTypeInfo: 'optional', stylistic: true},
    'prefer-response-static-json': {disableInCodeBlocks: 'tooStrict'},
    'prefer-set-methods': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-set-size': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-short-arrow-method': {stylistic: true},
    'prefer-simple-condition-first': {stylistic: true},
    'prefer-simple-sort-comparator': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-simplified-conditions': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-single-array-predicate': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-single-call': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-single-replace': {stylistic: true},
    'prefer-split-limit': {stylistic: true},
    'prefer-spread': {requiresTypeInfo: 'optional', stylistic: true, autofixDisabled: true},
    'prefer-string-pad-start-end': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-string-raw': {
      stylistic: true,
      autofixDisabled: [
        true,
        'transforms strings to `String.raw` expressions, which may cause type errors',
      ],
    },
    'prefer-string-repeat': {stylistic: true},
    'prefer-string-replace-all': {
      requiresTypeInfo: ['optional', 'indirect'],
      stylistic: true,
      disableInCodeBlocks: [false, 'TODO: reason was not recorded'],
    },
    'prefer-string-slice': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-string-starts-ends-with': {
      requiresTypeInfo: ['optional', 'indirect'],
      stylistic: [false, 'TODO: reason was not recorded'],
      disableInCodeBlocks: [false, 'TODO: reason was not recorded'],
    },
    'prefer-string-trim-start-end': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-structured-clone': {stylistic: true},
    'prefer-switch': {stylistic: true},
    'prefer-temporal': {requiresTypeInfo: 'optional'},
    'prefer-ternary': {stylistic: true},
    'prefer-then-catch': {requiresTypeInfo: 'optional'},
    'prefer-toggle-attribute': {requiresTypeInfo: ['optional', 'indirect'], stylistic: true},
    'prefer-top-level-await': {disableInCodeBlocks: 'runtimeOnly', cliFiles: 'error'},
    'prefer-type-error': {stylistic: true},
    'prefer-type-literal-last': {stylistic: true},
    'prefer-uint8array-base64': {requiresTypeInfo: 'optional'},
    'prefer-unary-minus': {stylistic: true},
    'prefer-unicode-code-point-escapes': {stylistic: true},
    'prefer-url-can-parse': {stylistic: true},
    'prefer-url-href': {requiresTypeInfo: 'optional', stylistic: true},
    'prefer-url-search-parameters': {requiresTypeInfo: ['optional', 'indirect']},
    'prefer-while-loop-condition': {stylistic: true},
    'prevent-abbreviations': {stylistic: true},
    'relative-url-style': {
      stylistic: true,
      disableInCodeBlocks: [false, 'TODO: reason was not recorded'],
    },
    'require-array-join-separator': {requiresTypeInfo: ['optional', 'indirect']},
    'require-array-sort-compare': {requiresTypeInfo: ['optional', 'indirect']},
    'single-line-block-comment-style': {stylistic: true},
    'switch-case-braces': {stylistic: true},
    'template-indent': {
      stylistic: true,
      prettierIncompatible: [
        false,
        "enabled in Prettier's own codebase; conflicts only in rare ternary+template cases: https://github.com/prettier/eslint-config-prettier/issues/281",
      ],
      disableInTestFiles: [true, 'triggered on inline snapshots'],
    },
    'text-encoding-identifier-case': {stylistic: true},
  },
});
