import {definePluginMetadata} from './shared';

export default definePluginMetadata('vue', {
  configs: ['vue'],
  isMainPlugin: true,
  docsUrl: 'https://eslint.vuejs.org',
  ruleDocsUrl: (ruleName) => `https://eslint.vuejs.org/rules/${ruleName}.html`,
  prettierLanguage: 'vue',
  rules: {
    'array-bracket-newline': {prettierIncompatible: true},
    'array-bracket-spacing': {prettierIncompatible: true},
    'array-element-newline': {prettierIncompatible: true},
    'arrow-spacing': {prettierIncompatible: true},
    'attribute-hyphenation': {stylistic: true},
    'attributes-order': {stylistic: true},
    'block-lang': {stylistic: true, disableInCodeBlocks: 'tooStrict'},
    'block-order': {stylistic: true},
    'block-spacing': {prettierIncompatible: true},
    'block-tag-newline': {prettierIncompatible: true},
    'brace-style': {prettierIncompatible: true},
    'comma-dangle': {prettierIncompatible: true},
    'comma-spacing': {prettierIncompatible: true},
    'comma-style': {prettierIncompatible: true},
    'component-name-in-template-casing': {stylistic: true},
    'custom-event-name-casing': {stylistic: true},
    'define-emits-declaration': {stylistic: true},
    'define-macros-order': {stylistic: true},
    'define-props-declaration': {stylistic: true, disableInCodeBlocks: 'tooStrict'},
    'define-props-destructuring': {disableInCodeBlocks: 'tooStrict'},
    'dot-location': {prettierIncompatible: true},
    'dot-notation': {stylistic: true},
    'first-attribute-linebreak': {stylistic: true, prettierIncompatible: true},
    'func-call-spacing': {prettierIncompatible: true},
    'html-closing-bracket-newline': {prettierIncompatible: true},
    'html-closing-bracket-spacing': {prettierIncompatible: true},
    'html-end-tags': {
      prettierIncompatible: [
        false,
        "not a formatting rule: catches genuinely malformed markup, so it's safe with Prettier: https://github.com/prettier/eslint-config-prettier/issues/365",
      ],
    },
    'html-indent': {prettierIncompatible: true},
    'html-quotes': {prettierIncompatible: true},
    'html-self-closing': {
      stylistic: true,
      prettierIncompatible: [false, 'configured by default in a Prettier-compatible way'],
    },
    'key-spacing': {prettierIncompatible: true},
    'keyword-spacing': {prettierIncompatible: true},
    'max-attributes-per-line': {prettierIncompatible: true},
    'max-len': {prettierIncompatible: true},
    'multi-word-component-names': {stylistic: true},
    'multiline-html-element-content-newline': {prettierIncompatible: true},
    'multiline-ternary': {prettierIncompatible: true},
    'mustache-interpolation-spacing': {prettierIncompatible: true},
    'no-console': {disableInCodeBlocks: 'runtimeOnly'},
    'no-extra-parens': {prettierIncompatible: true},
    'no-implicit-coercion': {stylistic: true},
    'no-multi-spaces': {prettierIncompatible: true},
    'no-negated-condition': {stylistic: true},
    'no-negated-v-if-condition': {stylistic: true},
    'no-setup-props-reactivity-loss': {
      disableInCodeBlocks: [
        false,
        'the lost reactivity is a real bug that readers would copy along with the snippet',
      ],
    },
    'no-spaces-around-equal-signs-in-attribute': {prettierIncompatible: true},
    'no-undef-components': {disableInCodeBlocks: 'runtimeOnly'},
    'no-unsupported-features': {disableInCodeBlocks: 'runtimeOnly'},
    'no-unused-components': {disableInCodeBlocks: 'unused'},
    'no-unused-emit-declarations': {disableInCodeBlocks: 'unused'},
    'no-unused-properties': {disableInCodeBlocks: 'unused'},
    'no-unused-refs': {disableInCodeBlocks: 'unused'},
    'no-unused-vars': {disableInCodeBlocks: 'unused'},
    'no-use-v-else-with-v-for': {stylistic: true},
    'no-use-v-if-with-v-for': {stylistic: true},
    'no-useless-mustaches': {stylistic: true},
    'object-curly-newline': {prettierIncompatible: true},
    'object-curly-spacing': {prettierIncompatible: true},
    'object-property-newline': {prettierIncompatible: true},
    'object-shorthand': {stylistic: true},
    'operator-linebreak': {prettierIncompatible: true},
    'order-in-components': {stylistic: true},
    'padding-line-between-blocks': {stylistic: true},
    'prefer-separate-static-class': {stylistic: true},
    'prefer-template': {stylistic: true},
    'prefer-true-attribute-shorthand': {stylistic: true},
    'prefer-use-template-ref': {stylistic: true},
    'quote-props': {prettierIncompatible: true},
    'require-explicit-slots': {stylistic: true},
    'require-macro-variable-name': {
      stylistic: true,
      disableInCodeBlocks: [false, 'only reads the macro calls of the snippet itself'],
    },
    'require-prop-types': {disableInCodeBlocks: 'tooStrict'},
    'require-v-for-key': {
      disableInCodeBlocks: [
        false,
        'a missing key causes real rendering bugs that readers would copy along with the snippet',
      ],
    },
    'script-indent': {prettierIncompatible: true},
    'singleline-html-element-content-newline': {prettierIncompatible: true},
    'slot-name-casing': {stylistic: true},
    'space-in-parens': {prettierIncompatible: true},
    'space-infix-ops': {prettierIncompatible: true},
    'space-unary-ops': {prettierIncompatible: true},
    'template-curly-spacing': {prettierIncompatible: true},
    'v-bind-style': {stylistic: true},
    'v-for-delimiter-style': {stylistic: true},
    'v-on-event-hyphenation': {stylistic: true},
    'v-on-handler-style': {stylistic: true},
    'v-slot-style': {stylistic: true},
  },
});
