import {eslintConfigInternal} from '../../src/config-un/config';

// `testMode` force-enables Configs, but not the sub-configs gated on an installed package,
// so these have to be declared explicitly for the order below to be complete
beforeEach(() => {
  addInstalledPackages({'jest-extended': '7.0.0', prettier: '3.9.6', 'react-dom': '19.2.7'});
});

describe('cascade order', () => {
  it('resolves the flat configs in a stable order', async () => {
    const {configs} = await eslintConfigInternal(
      // Both options are environment-dependent by default: caching is on inside editors,
      // and offline mode follows an env var. Pinning them keeps the order reproducible
      {cacheConfigs: false, offlineMode: false},
      {testMode: true},
    );

    expect(configs.map(({name}) => name).join('\n')).toMatchInlineSnapshot(`
      "eslint-config-un/global-setup/plugins
      eslint-config-un/ignores/global
      eslint-config-un/ignores/gitignore
      eslint-config-un/global-setup/language-options
      eslint-config-un/global-setup/language-options/commonjs
      eslint-config-un/antfu
      eslint-config-un/arrow-return-style
      eslint-config-un/ava
      eslint-config-un/ava/package.json
      eslint-config-un/aws-cdk
      eslint-config-un/aws-cdk/@type-information
      eslint-config-un/barrel-files
      eslint-config-un/better-tailwindcss
      eslint-config-un/boundaries
      eslint-config-un/case-police
      eslint-config-un/clsx
      eslint-config-un/command
      eslint-config-un/compat
      eslint-config-un/cspell
      eslint-config-un/css
      eslint-config-un/css-in-js
      eslint-config-un/cypress
      eslint-config-un/cypress/no-only-tests
      eslint-config-un/de-morgan
      eslint-config-un/depend
      eslint-config-un/docusaurus
      eslint-config-un/drizzle
      eslint-config-un/e18e/modernization
      eslint-config-un/e18e/modernization/@type-information
      eslint-config-un/e18e/module-replacements
      eslint-config-un/e18e/performance-improvements
      eslint-config-un/e18e/performance-improvements/@type-information
      eslint-config-un/ember/glimmer-templates
      eslint-config-un/ember
      eslint-config-un/ember/@type-information
      eslint-config-un/ember/tests
      eslint-config-un/ember/no-only-tests
      eslint-config-un/erasable-syntax-only
      eslint-config-un/eslint-comments
      eslint-config-un/eslint-plugin
      eslint-config-un/eslint-plugin/@type-information
      eslint-config-un/expect-type
      eslint-config-un/expect-type/@type-information
      eslint-config-un/expo
      eslint-config-un/file-progress
      eslint-config-un/format/prettier
      eslint-config-un/functional
      eslint-config-un/functional/@type-information
      eslint-config-un/header
      eslint-config-un/headers
      eslint-config-un/html
      eslint-config-un/import
      eslint-config-un/import-integrity
      eslint-config-un/import-zod
      eslint-config-un/jest
      eslint-config-un/jest/ts
      eslint-config-un/jest/extended
      eslint-config-un/jest-dom
      eslint-config-un/js
      eslint-config-un/js/stylistic_spaced-comment
      eslint-config-un/jsdoc
      eslint-config-un/jsdoc/ts
      eslint-config-un/js-inline
      eslint-config-un/js-inline/js-inside-html-inside-markdown
      eslint-config-un/json/json
      eslint-config-un/json/jsonc
      eslint-config-un/json/json5
      eslint-config-un/jsonc/all
      eslint-config-un/json-schema-validator/js-ts
      eslint-config-un/json-schema-validator/json
      eslint-config-un/json-schema-validator/yaml
      eslint-config-un/json-schema-validator/toml
      eslint-config-un/jsx-a11y
      eslint-config-un/lit
      eslint-config-un/lit-a11y
      eslint-config-un/lockfile
      eslint-config-un/lockfile/parser/json
      eslint-config-un/lockfile/parser/yaml
      eslint-config-un/lockfile/parser/jsonc
      eslint-config-un/lockfile/package.json
      eslint-config-un/markdown-links
      eslint-config-un/markdown-preferences
      eslint-config-un/math
      eslint-config-un/mobx
      eslint-config-un/mocha
      eslint-config-un/mocha/no-only-tests
      eslint-config-un/module-interop
      eslint-config-un/nest-js
      eslint-config-un/nest-js/@type-information
      eslint-config-un/nextjs
      eslint-config-un/ngrx
      eslint-config-un/ngrx/@type-information
      eslint-config-un/unicorn
      eslint-config-un/unicorn/@type-information
      eslint-config-un/unicorn/any-language
      eslint-config-un/unicorn/css
      eslint-config-un/unicorn/html
      eslint-config-un/unicorn/json
      eslint-config-un/unicorn/markdown
      eslint-config-un/node
      eslint-config-un/node-dependencies
      eslint-config-un/no-only-tests
      eslint-config-un/no-relative-import-paths
      eslint-config-un/no-secrets
      eslint-config-un/no-secrets/json
      eslint-config-un/no-unsanitized
      eslint-config-un/nx
      eslint-config-un/nx/json
      eslint-config-un/package-json
      eslint-config-un/perfectionist
      eslint-config-un/playwright
      eslint-config-un/pnpm/package.json
      eslint-config-un/pnpm/pnpm-workspace-yaml
      eslint-config-un/prefer-arrow-functions
      eslint-config-un/promise
      eslint-config-un/qunit
      eslint-config-un/qwik
      eslint-config-un/react/plugin-original
      eslint-config-un/react/allow-default-export-in-jsx-files
      eslint-config-un/react/hooks
      eslint-config-un/react/x
      eslint-config-un/react/x/rules-type-aware
      eslint-config-un/react/x/rules-type-aware/@type-information
      eslint-config-un/react/dom
      eslint-config-un/react/refresh
      eslint-config-un/react/you-might-not-need-an-effect
      eslint-config-un/regexp
      eslint-config-un/remeda
      eslint-config-un/ripple/setup
      eslint-config-un/ripple
      eslint-config-un/rxjs
      eslint-config-un/security
      eslint-config-un/solid
      eslint-config-un/sonar
      eslint-config-un/sonar/@type-information
      eslint-config-un/sql
      eslint-config-un/storybook
      eslint-config-un/storybook/main
      eslint-config-un/stylistic
      eslint-config-un/stylistic/spaced-comment
      eslint-config-un/tailwind
      eslint-config-un/tanstack-query
      eslint-config-un/tanstack-router
      eslint-config-un/tanstack-start
      eslint-config-un/testing-library/angular
      eslint-config-un/testing-library/angular/no-only-tests
      eslint-config-un/testing-library/react
      eslint-config-un/testing-library/react/no-only-tests
      eslint-config-un/testing-library/svelte
      eslint-config-un/testing-library/svelte/no-only-tests
      eslint-config-un/testing-library/vue
      eslint-config-un/testing-library/vue/no-only-tests
      eslint-config-un/toml
      eslint-config-un/tree-shaking
      eslint-config-un/tsdoc
      eslint-config-un/turbo
      eslint-config-un/un
      eslint-config-un/unhead
      eslint-config-un/unnecessary-abstractions
      eslint-config-un/unocss
      eslint-config-un/unused-imports/no-unused-imports
      eslint-config-un/vitest
      eslint-config-un/vitest/ts
      eslint-config-un/web-components
      eslint-config-un/yaml
      eslint-config-un/yaml/pnpm-workspace.yaml
      eslint-config-un/you-dont-need-lodash-underscore
      eslint-config-un/zod
      eslint-config-un/zod/mini
      eslint-config-un/zod/core
      eslint-config-un/zod-openapi
      eslint-config-un/zod-openapi/@type-information
      eslint-config-un/ts/non-type-aware/setup
      eslint-config-un/ts/non-type-aware/rules
      eslint-config-un/ts/disable-handled-by-ts-compiler-rules
      eslint-config-un/ts/overrides
      eslint-config-un/ts/type-aware/setup
      eslint-config-un/ts/type-aware/rules
      eslint-config-un/ts/dts
      eslint-config-un/angular/general
      eslint-config-un/angular/template
      eslint-config-un/astro
      eslint-config-un/astro/setup
      eslint-config-un/jsx-a11y/astro
      eslint-config-un/es
      eslint-config-un/github-actions
      eslint-config-un/graphql/processor
      eslint-config-un/graphql
      eslint-config-un/svelte/setup
      eslint-config-un/svelte
      eslint-config-un/svelte/@type-information
      eslint-config-un/svelte/enforce-typescript-in-script-section
      eslint-config-un/vue/setup
      eslint-config-un/vue
      eslint-config-un/vue/allow-single-word-component-names
      eslint-config-un/vue/allow-implicit-slots
      eslint-config-un/vue/allow-default-export
      eslint-config-un/vue/enforce-typescript-in-script-section
      eslint-config-un/vue/a11y
      eslint-config-un/vue/scoped-css
      eslint-config-un/check-file
      eslint-config-un/formatjs
      eslint-config-un/markdown/markdown
      eslint-config-un/markdown/setup/code-blocks-processor
      eslint-config-un/markdown/code-blocks
      eslint-config-un/markdown/format-fenced-code-blocks
      eslint-config-un/mdx/mdx
      eslint-config-un/mdx/setup/code-blocks-processor
      eslint-config-un/mdx/code-blocks
      eslint-config-un/mdx/format-fenced-code-blocks
      eslint-config-un/config-files
      eslint-config-un/allow-default-export
      eslint-config-un/cli
      eslint-config-un/tests
      eslint-config-un/no-prettier-incompatible-rules
      eslint-config-un/no-stylistic-rules"
    `);
  });
});
