// Generated by auto imports
export {}
declare global {
  const computed: typeof import('vue').computed
  const useFetch: typeof import('nuxt/app').useFetch
  const useMyComposable: typeof import('../../app/composables/use-my-composable').useMyComposable
  const vMyDirective: typeof import('../../app/composables/v-my-directive').vMyDirective
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Ref } from 'vue'
  import('vue')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
  }
}
