// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useMySharedUtil: typeof import('../../shared/utils/use-my-shared-util').useMySharedUtil
}
