name: CI matrix tests
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: number
      eslint-version:
        required: true
        type: number

jobs:
  test-config:
    name: Un config test
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ inputs.node-version }}
      - run: pnpm i eslint@${{ inputs.eslint-version }}
        if: inputs.eslint-version != 9 # TODO temp, already installed and installation gets stuck on node 22
      - run: pnpm test:config
  test-vitest:
    name: Vitest
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ inputs.node-version }}
      - run: pnpm i eslint@${{ inputs.eslint-version }}
        if: inputs.eslint-version != 9 # TODO temp, already installed and installation gets stuck on node 22
      - run: pnpm test:vitest
